[package]
name = "scrappy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0"

[dev-dependencies]
insta = "1.29.0"
test-case = "3.1.0"
